### ISSUE TITLE
FIT files from Siril

### ISSUE THREAD

**Issue by chges100** [Steffenhir/Background_extraction#22]
OS: Ubuntu Linux 20.04
Program version: v0.0.5

When loading a 32bit floating point .fit file exported with Siril, the following exception is thrown:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1892, in __call__
  File "gui.py", line 236, in menu_open_clicked
  File "gui.py", line 307, in set_image
AttributeError: 'NoneType' object has no attribute 'shape'

Happens with 16-bit fit files from Siril, too.

**Comment by schmelly** [comment]
I cannot reproduce this issue with my own Siril .fit file on Ubuntu 21.10. Can you please share your image?

**Comment by chges100** [comment]
I think I found the issue - Siril has the option to use a compression algorithm (Rice) which makes the fit files reasonably smaller without too much quality loss. With this option activated, we cannot open the file. With an uncompressed fits file it works fine.

**Comment by chges100** [comment]
I just changed to "enhancement"  - i will leave this issue open for documentation, but I think it is not a top priority issue.

**Comment by cissou8** [comment]
astropy.fits module can handle compressed fits as well (both reading and writing).
Just wrote a quick and dirty patch but you may want to handle more complex cases. For instance, Siril also write fitseq with the same .fits extension, in which case the table length would be >2.
[read_compressed_fits.zip](https://github.com/Steffenhir/GraXpert/files/8647544/read_compressed_fits.zip)

**Comment by Steffenhir** [comment]
Thank you very much! We will take a look how we can handle the more complex cases as well.
